// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ipfs.echo.WWW {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TextData;
		
		protected System.Web.UI.WebControls.TextBox DeviceKey;
		
		protected System.Web.UI.WebControls.CheckBox Overwrite;
		
		protected System.Web.UI.WebControls.Button GoButton;
	}
}
